# Site settings
baseurl = "/"
themesDir = "./"
languageCode = "en-us"
title = "Jacob Ward"
theme = ""
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "jacobwarduk"

[params]
	name = "Jacob Ward"
	description = "Jacob is a Contract Front End & JavaScript developer. This is his little place on the web to play around and occasionally write stuff about what he does."
	bio = "Contract Front End & JavaScript Developer"
	# Enter optionally your twitter account
	twitter = "jacobwarduk"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""

	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Contract Front End & JavaScript Programmer"
	tweet = ""
	facebook = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter-square      = "https://www.twitter.com/jacobwarduk"
    linkedin-square     = "https://www.linkedin.com/in/jacobwarduk/"
    github-square       = "https://github.com/jacobwarduk"
    rss-square          = "http://jacobward.io/index.xml"
